language: cpp

# sources  list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json,
# packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

compiler: gcc
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
    packages: [ 'g++-5', 'libstdc++-5-dev', 'cmake' ]
env: CMAKE_BUILD_TYPE=Release BOOST_VERSION=1.60.0 BOOST_BUILD=true

sudo: false
cache:
  directories:
  - $HOME/.ccache
  - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0

install: |
  #!/bin/bash
  set -eu

  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  mkdir -p latest-gcc-symlinks

  export CXX="g++-5" CC="gcc-5" BOOST_TOOLSET=gcc; 
  ln -s /usr/bin/${CXX} latest-gcc-symlinks/g++ 
  ln -s /usr/bin/${CC} latest-gcc-symlinks/gcc

  export PATH=$PWD/latest-gcc-symlinks:$PATH

  # Install newer boost compatible with gcc 5.
  ############################################################################
  # Install Boost headers
  ############################################################################

  BOOST_DIR=${DEPS_DIR}/boost-${BOOST_VERSION}
  if [[ -z "$(ls -A ${BOOST_DIR})" ]]; then
    BOOST_URL="http://venediktov.github.io/boost_${BOOST_VERSION//\./_}.tar.gz"
    mkdir -p ${BOOST_DIR}
    { travis_retry wget  -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
  fi
  CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
  export CMAKE_OPTIONS

  ############################################################################
  # Install Boost.Build
  ############################################################################

  (echo "using gcc : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" > ~/user-config.jam)
  (cd ${BOOST_DIR} && ./bootstrap.sh --with-toolset=${BOOST_TOOLSET} --with-libraries=program_options,system,regex,serialization,log,date_time && ./b2 toolset=${BOOST_TOOLSET} install --prefix=${BOOST_DIR})
  export PATH=${BOOST_DIR}/bin:${PATH}

  ############################################################################
  # Install a recent CMake
  ############################################################################

  CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
  mkdir  cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  export PATH=${DEPS_DIR}/cmake/bin:${PATH}

before_script: |
  #!/bin/bash
  set -eu

  ccache -V && ccache --show-stats && ccache --zero-stats

script: |
  #!/bin/bash
  set -eu

  $CXX --version
  cmake --version

  ############################################################################
  # Go back to the root of the project and setup the build directory
  ############################################################################
  cd ${TRAVIS_BUILD_DIR}
  mkdir build && cd build
  cmake .. ${CMAKE_OPTIONS}
  make -j4 VERBOSE=1
  make test
  ccache --show-stats


