language: cpp
script: |
    #!/bin/bash
    set -eu
    mkdir build
    cd build
    cmake ..
    cmake --build .
    cmake --build . --target test
addons:
    apt:
        sources: ['george-edison55-precise-backports']
        packages: ['cmake', 'cmake-data']
